/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
//$('#dropdown li').on('click', function(){
//    alert($(this).text());
//});

var $drop = $('#dropdown li a');
$drop.each(function(index, element) {
    console.log(this);
    var $item = $(this);
    var $cityName = $item.data("location");
    var yql = $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"'+ $cityName +'")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', function (data) {
        console.log(data);
        var currentTemp = Math.round((data.query.results.channel.item.condition.temp-32)*(5/9));
        $item.text( $item.text() + "  " +currentTemp + "℃");
 //       $("button").text($cityName);
    })
});
$drop.on("click", function(e) {
    var $item = $(this);
    var $cityName = $item.data("location");
    var yql = $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"'+ $cityName +'")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', function (data) {
        console.log(data);
        var currentTemp = Math.round((data.query.results.channel.item.condition.temp-32)*(5/9));
        var currentWeather = data.query.results.channel.item.condition.text;
        var currentDate = data.query.results.channel.item.forecast[0].date;
        var tomorrowTemp = Math.round((-32)*(5/9));
        var tomorrowWeather = data.query.results.channel.item.forecast[0].text;
        var tomorrowDate = data.query.results.channel.item.forecast[1].date;
        var nextTemp = Math.round((data.query.results.channel.item.condition.temp-32)*(5/9));
        var nextWeather = data.query.results.channel.item.condition.text;
        var nextDate = data.query.results.channel.item.forecast[2].date;
        $(".temperature").text(currentTemp);
        $(".currentweather").text(currentWeather);
        $(".date").text(currentDate);
        $item.text($item.text());
        $(".cityfirst").text($cityName);
        $("#datetime th:nth-of-type(1)").text(tomorrowDate);
    })
    });

$("#firstSelection").trigger("click") ;