/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
//$('#dropdown li').on('click', function(){
//    alert($(this).text());
//});

var $drop = $('#dropdown li a');
$drop.each(function(index, element) {
    console.log(this);
    var $item = $(this);
    var $cityName = $item.data("location");
    var yql = $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"'+ $cityName +'")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', function (data) {
        console.log(data);
        var currentTemp = Math.round(((data.query.results.channel.item.condition.temp)-32)*(5/9));
        $item.text( $item.text() + "  " +currentTemp + "℃");
 //       $("button").text($cityName);
    })
});
$drop.on("click", function(e) {
    var $item = $(this);
    var $cityName = $item.data("location");
    var yql = $.getJSON('https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"'+ $cityName +'")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', function (data) {
        console.log(data);
        var currentTemp = Math.round((data.query.results.channel.item.condition.temp-32)*(5/9));
        var currentWeather = data.query.results.channel.item.condition.text;
        var currentDate = data.query.results.channel.item.forecast[0].date;
        var tomorrowLow = Math.round((data.query.results.channel.item.forecast[1].low-32)*(5/9));
        var tomorrowHigh = Math.round((data.query.results.channel.item.forecast[1].high-32)*(5/9));
        var tomorrowWeather = data.query.results.channel.item.forecast[1].text;
        var tomorrowDate = data.query.results.channel.item.forecast[1].date;
        var nextLow = Math.round((data.query.results.channel.item.forecast[2].low-32)*(5/9));
        var nextHigh = Math.round((data.query.results.channel.item.forecast[2].high-32)*(5/9));
        var nextWeather = data.query.results.channel.item.forecast[2].text;
        var nextDate = data.query.results.channel.item.forecast[2].date;
        var afterLow = Math.round((data.query.results.channel.item.forecast[3].low-32)*(5/9));
        var afterHigh = Math.round((data.query.results.channel.item.forecast[3].high-32)*(5/9));
        var afterWeather = data.query.results.channel.item.forecast[3].text;
        var afterDate = data.query.results.channel.item.forecast[3].date;
        var canvasToday = data.query.results.channel.item.condition.code;
        var canvasDay1 = data.query.results.channel.item.forecast[1].code;
        var canvasDay2 = data.query.results.channel.item.forecast[2].code;
        var canvasDay3 = data.query.results.channel.item.forecast[3].code;
        $(".temperature").text(currentTemp);
        $("td:nth-of-type(1) .low").text(tomorrowLow);
        $("td:nth-of-type(2) .low").text(nextLow);
        $("td:nth-of-type(3) .low").text(afterLow);
        $("td:nth-of-type(1) .high").text(tomorrowHigh);
        $("td:nth-of-type(2) .high").text(nextHigh);
        $("td:nth-of-type(3) .high").text(afterHigh);
        $("#datetime th:nth-of-type(1)").text(tomorrowDate);
        $("#datetime th:nth-of-type(2)").text(nextDate);
        $("#datetime th:nth-of-type(3)").text(afterDate);
        $(".currentweather").text(currentWeather);
        $(".date").text(currentDate);
        $item.text($item.text());
        $(".cityfirst").text($cityName);
        skyIcon("today", canvasToday);
        skyIcon("day1", canvasDay1);
        skyIcon("day2", canvasDay2);
        skyIcon("day3", canvasDay3);

    })
    });
var skyIcon = function(canvasName, code) {
    switch(code) {
        case "0":
            skycons.set(canvasName, Skycons.SLEET);
            break;
        case "1":
            skycons.set(canvasName, Skycons.SLEET);
            break;
        case "2":
            skycons.set(canvasName, Skycons.SLEET);
            break;
        case "3":
            skycons.set(canvasName, Skycons.SLEET);
            break;
        case "4":
            skycons.set(canvasName, Skycons.SLEET);
            break;
        case "5":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "6":
            skycons.set(canvasName, Skycons.SLEET);
            break;
        case "7":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "8":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "9":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "10":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "11":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "12":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "13":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "14":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "15":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "16":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "17":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "18":
            skycons.set(canvasName, Skycons.SLEET);
            break;
        case "19":
            skycons.set(canvasName, Skycons.FOG);
            break;
        case "20":
            skycons.set(canvasName, Skycons.FOG);
            break;
        case "21":
            skycons.set(canvasName, Skycons.FOG);
            break;
        case "22":
            skycons.set(canvasName, Skycons.FOG);
            break;
        case "23":
            skycons.set(canvasName, Skycons.FOG);
            break;
        case "24":
            skycons.set(canvasName, Skycons.WIND);
            break;
        case "25":
            skycons.set(canvasName, Skycons.WIND);
            break;
        case "26":
            skycons.set(canvasName, Skycons.CLOUDY);
            break;
        case "27":
            skycons.set(canvasName, Skycons.CLOUDY);
            break;
        case "28":
            skycons.set(canvasName, Skycons.CLOUDY);
            break;
        case "29":
            skycons.set(canvasName, Skycons.PARTLY_CLOUDY_NIGHT);
            break;
        case "30":
            skycons.set(canvasName, Skycons.PARTLY_CLOUDY_DAY);
            break;
        case "31":
            skycons.set(canvasName, Skycons.CLEAR_NIGHT);
            break;
        case "32":
            skycons.set(canvasName, Skycons.CLEAR_DAY);
            break;
        case "33":
            skycons.set(canvasName, Skycons.CLEAR_NIGHT);
            break;
        case "34":
            skycons.set(canvasName, Skycons.CLEAR_DAY);
            break;
        case "35":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "36":
            skycons.set(canvasName, Skycons.CLEAR_DAY);
            break;
        case "37":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "38":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "39":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "40":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "41":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "42":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "43":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "44":
            skycons.set(canvasName, Skycons.CLOUDY);
            break;
        case "45":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        case "46":
            skycons.set(canvasName, Skycons.SNOW);
            break;
        case "47":
            skycons.set(canvasName, Skycons.RAIN);
            break;
        default:
            skycons.set(canvasName, Skycons.CLEAR_DAY);
    };
};
$("#firstSelection").trigger("click") ;